language: php

php:
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

script: VERBOSE=true ./tests/run-tests.sh -s tests/HostBoxTests/

before_script:
  - composer install --no-interaction --prefer-source --dev

after_failure:
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
